### ISSUE TITLE
Upper and lower case of table names

### ISSUE THREAD

**Issue by pavlas77** [SuperOfficeDocs/database#12]
from: | Espen Steen <Espen.Steen@crminsight.no>

Lately I have found the table reference documentation to be imprecise when it comes to upper and lower case.

Example: https://docs.superoffice.com/database/tables/udeffield.html#fields
The documentation states the table name is "udeffield" in the main screen, and it says that it is "Udeffield" on the left hand menu. Neither is correct, the correct name is "UDefField". 

Its important to have the correct name when for example using SearchEngine in CRMSCript which is case sensitive. I just spent a good amount of time to figure out why my SearchEngine wasnt getting any results when searching for "udeffield"...

**Comment by SuperOfficeDevNet** [comment]
Fixed in commit [https://github.com/SuperOfficeDocs/database/commit/2fd03ea4db57523861ba35db11a9a8d4c8f59238]
